config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  get 'products/index'

  get 'line_items/create'

  get 'line_items/update'

  get 'line_items/destroy'

  get 'carts/show'

  resources :line_items, only: [:create, :update, :destroy], defaults: { format: 'js' }
  resource :cart, only: [:show]
  resources :charges
  resources :products

  devise_for :users, :controllers => {:registrations => "registrations"}



  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'

  resources :charges, only: [:new, :create]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  before_validation :set_order_status
  belongs_to :order_status
  has_many :line_items
  before_save :update_subtotal

  def subtotal
    line_items.collect { |oi| oi.valid? ? (oi.quantity.to_i * oi.unit_price.to_f) : 0 }.sum
  end
  private
  def set_order_status
    self.order_status_id = 1 if self.order_status_id.nil?
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end


end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
  validates :name, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :line_items
  attr_writer :remove_photo

  def remove_photo
    @remove_photo || false
  end



  before_validation { self.photo.clear if self.remove_photo == '1' }

  has_attachment :photo

  validates :name, uniqueness: true
  validates :name, :description, :size, :stock, :price, presence: true
  validates :stock, numericality: { only_integer: true }
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }

  mount_uploader :photo, PhotoUploader
  default_scope { where(active: true)}
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers

  validates :name, presence: true
  validates :pst, presence: true
  validates :gst, presence: true
  validates :hst, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :customer

  before_save { |user| user.username = user.username.downcase }

  validates :username, presence: true
  validates :username, uniqueness: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates_confirmation_of :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new(order_status_id: 1)
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:email, :username, :password, :password_confirmation)
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @line_items = current_order.line_items
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Rails Stripe customer',
        :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def create
    @order = current_order
    @line_item = @order.line_items.new(line_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @line_item = @order.line_items.find(params[:id])
    @line_item.update_attributes(line_item_params)
    @line_items = @order.line_items
  end

  def destroy
    @order = current_order
    @line_item = @order.line_items.find(params[:id])
    @line_item.destroy
    @line_items = @order.line_items
  end

  private

  def line_item_params
    params.require(:line_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @line_item = current_order.line_items.new
  end
  Product.includes(:photo_files).all

  def show
    @product = Product.find(params[:id])
    @line_item = current_order.line_items.new
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/line_items/create.html.erb
<h1>LineItems#create</h1>
<p>Find me in app/views/line_items/create.html.erb</p>

app/views/line_items/create.js.erb
<% if @order.errors.any? || @line_item.errors.any? %>
alert("not valid.")
<% else %>
$(".cart-text").html("<%= escape_javascript(render 'layouts/user_cart_text') %>")
<% end %>

app/views/line_items/destroy.html.erb
<h1>LineItems#destroy</h1>
<p>Find me in app/views/line_items/destroy.html.erb</p>

app/views/line_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/user_cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/line_items/update.html.erb
<h1>LineItems#update</h1>
<p>Find me in app/views/line_items/update.html.erb</p>

app/views/line_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/user_cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/products/_product_row.html.erb
<div class="column">

<%= form_for line_item, remote: true do |f| %>

      <a href="<%= product_path(product) %>">
        <%= image_tag product.photo.url(:thumbnail) if product.photo? %>
        <p><%=product.name %></p>
        <p class="text-right"><%= number_to_currency product.price %></p>
        <div class="input-group">
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "See more", class: "btn btn-primary" %>
          </div>
        </div>


  <% end %>
  </div>

app/views/products/index.html.erb
<div class="row column text-center">
  <h4>Our Newest Products</h4>
  <hr>
</div>
<div class="row small-up-2 large-up-4">
  <% @products.each do |product| %>
      <%= render "product_row", product: product, line_item: @line_item %>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="column">

  <%= form_for @line_item, remote: true do |f| %>

<%= image_tag @product.photo.url(:thumbnail) if @product.photo? %>
<p><%=@product.name %></p>
      <p><strong>Description: </strong><%=@product.description %></p>
      <p><strong>Stock: </strong><%=@product.stock %></p>
<p class="text-right"><%= number_to_currency @product.price %></p>
<div class="input-group">
  <%= f.number_field :quantity, value: 1, class: "form-control", min: 1, max: @product.stock %>
  <div class="input-group-btn">
    <%= f.hidden_field :product_id, value: @product.id %>
    <%= f.submit "Add to Cart", class: "btn btn-primary" %>
  </div>
</div>
  <% end %>

</div>