config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  get 'products/index'

  get 'line_items/create'

  get 'line_items/update'

  get 'line_items/destroy'

  get 'carts/show'

  resources :line_items, only: [:create, :update, :destroy], defaults: { format: 'js' }
  resource :cart, only: [:show]
  resources :charges
  resources :products

  devise_for :users, :controllers => {:registrations => "registrations"}



  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'

  resources :charges, only: [:new, :create]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  before_validation :set_order_status
  belongs_to :order_status
  has_many :line_items
  before_save :update_subtotal

  def subtotal
    line_items.collect { |oi| oi.valid? ? (oi.quantity.to_i * oi.unit_price.to_f) : 0 }.sum
  end
  private
  def set_order_status
    self.order_status_id = 1 if self.order_status_id.nil?
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end


end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
  validates :name, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :line_items
  attr_writer :remove_photo

  def remove_photo
    @remove_photo || false
  end



  before_validation { self.photo.clear if self.remove_photo == '1' }

  has_attachment :photo

  validates :name, uniqueness: true
  validates :name, :description, :size, :stock, :price, presence: true
  validates :stock, numericality: { only_integer: true }
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }

  mount_uploader :photo, PhotoUploader
  default_scope { where(active: true)}
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers

  validates :name, presence: true
  validates :pst, presence: true
  validates :gst, presence: true
  validates :hst, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :customer

  before_save { |user| user.username = user.username.downcase }

  validates :username, presence: true
  validates :username, uniqueness: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates_confirmation_of :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new(order_status_id: 1)
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:email, :username, :password, :password_confirmation)
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @line_items = current_order.line_items
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Rails Stripe customer',
        :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def create
    @order = current_order
    @line_item = @order.line_items.new(line_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @line_item = @order.line_items.find(params[:id])
    @line_item.update_attributes(line_item_params)
    @line_items = @order.line_items
  end

  def destroy
    @order = current_order
    @line_item = @order.line_items.find(params[:id])
    @line_item.destroy
    @line_items = @order.line_items
  end

  private

  def line_item_params
    params.require(:line_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @line_item = current_order.line_items.new
  end
  Product.includes(:photo_files).all

  def show
    @product = Product.find(params[:id])
    @line_item = current_order.line_items.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-4">

    </div>
    <div class="col-xs-2">

      <%= form_for line_item, remote: true do |f| %>

          <div class="cart-row">
            <p><%= product.name %></p>
            <p><%= number_to_currency line_item.unit_price %></p>
              <%= f.number_field :quantity, value: line_item.quantity.to_i, class: "form-control", min: 1, size: 10 %>
              <%= f.hidden_field :product_id, value: product.id %>
              <div class="btn-group">
                <%= f.submit "Update Quantity", class: "btn btn-primary" %>
                <%= link_to "Delete", line_item, { data: { confirm: "Are you sure you wish to delete the product '#{line_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
                <p class="text-right">Total Price: <span style="color: green"><%= number_to_currency line_item.total_price %></span></p>
              </div>

          </div>

      <% end %>
    </div>

  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@line_item.nil? && @line_item.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @line_item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<% if @line_items.size == 0 %>
    <p class="text-center">
      There are no items in your shopping cart.
    </p>
    <p class="text-center">
      <%= link_to "Go back", root_path %> and buy something!
    </p>
<% else %>
    <% @line_items.each do |line_item| %>
        <%= render 'carts/cart_row', product: line_item.product, line_item: line_item, show_total: true %>
    <% end %>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%= number_to_currency(@charge.amount / 100) %></strong>!</h2>

<h3>Stripe Customer</h3>
<%= debug @customer %>

<h3>Stripe Charge</h3>
<%= debug @charge %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
    <article>
      <% if flash[:error].present? %>
          <div id="error_explanation">
            <p><%= flash[:error] %></p>
          </div>
      <% end %>
      <label class="amount">
        <span>Amount: $500</span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="testing"
            data-amount="500"
            data-locale="auto"></script>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<ul>

</ul>