config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  get 'products/index'

  get 'line_items/create'

  get 'line_items/update'

  get 'line_items/destroy'

  get 'carts/show'

  resources :line_items, only: [:create, :update, :destroy], defaults: { format: 'js' }
  resource :cart, only: [:show]
  resources :charges
  resources :products

  devise_for :users, :controllers => {:registrations => "registrations"}



  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'

  resources :charges, only: [:new, :create]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  before_validation :set_order_status
  belongs_to :order_status
  has_many :line_items
  before_save :update_subtotal

  def subtotal
    line_items.collect { |oi| oi.valid? ? (oi.quantity.to_i * oi.unit_price.to_f) : 0 }.sum
  end
  private
  def set_order_status
    self.order_status_id = 1 if self.order_status_id.nil?
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end


end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
  validates :name, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :line_items
  attr_writer :remove_photo

  def remove_photo
    @remove_photo || false
  end



  before_validation { self.photo.clear if self.remove_photo == '1' }

  has_attachment :photo

  validates :name, uniqueness: true
  validates :name, :description, :size, :stock, :price, presence: true
  validates :stock, numericality: { only_integer: true }
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }

  mount_uploader :photo, PhotoUploader
  default_scope { where(active: true)}
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers

  validates :name, presence: true
  validates :pst, presence: true
  validates :gst, presence: true
  validates :hst, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :customer

  before_save { |user| user.username = user.username.downcase }

  validates :username, presence: true
  validates :username, uniqueness: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates_confirmation_of :password
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @line_items = current_order.line_items
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Rails Stripe customer',
        :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @line_item = current_order.line_items.new
  end
  Product.includes(:photo_files).all

  def show
    @product = Product.find(params[:id])
    @line_item = current_order.line_items.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_navigation.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="menu">
      <h3>JS Sporting Apparel</h3>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <%= render 'layouts/user_cart_text' %>
    </ul>
  </div>
</div>
<div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
  <ul class="orbit-container">
    <button class="orbit-previous" aria-label="previous"><span class="show-for-sr">Previous Slide</span>&#9664;</button>
    <button class="orbit-next" aria-label="next"><span class="show-for-sr">Next Slide</span>&#9654;</button>
    <li class="orbit-slide is-active">
      <%= cl_image_tag("hockey-header_vhjbiv.jpg") %>
    </li>
    <li class="orbit-slide">
      <%= cl_image_tag("football-header_itkdip.jpg") %>
    </li>
    <li class="orbit-slide">
      <%= cl_image_tag("soccer-header_bxaavh.jpg") %>
    </li>
    <li class="orbit-slide">
      <%= cl_image_tag("basketball-header_qcrbjk.jpg") %>
    </li>

  </ul>
</div>
<div class="row" align="center">
  <div class="small-12 columns">
    <p class="links">
      <a href="/products">Home</a>
      <a href="/products">Products</a>
      <a href="#">About</a>
      <a href="#">Contact</a>
    </p>
  </div>
</div>
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>
<script>
    $(document).foundation();
</script>

app/views/layouts/_user_cart_text.html.erb
<% if user_signed_in? %>
    <li>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    </li>
    <li>
      <%= current_user.email %>
    </li>
    <li>
      <%= link_to "#{current_order.line_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>
    </li>
<% else %>
    <li>
      <%= link_to "Sign In", new_user_session_path %>
    </li>
    <li>
      <%= link_to "Register", new_user_registration_path %>
    </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
  <%= yield %>

  </body>
</html>